### ISSUE TITLE
Investigate why some agents are always down

### ISSUE THREAD

**Issue by ArmandMeppa** [ADORSYS-GIS/wazuh-agent#10]

**Comment by MarantosGeorge** [comment]
Issue with Wazuh Dashboard. Waiting on Fix to investigate this Issue.

**Comment by Calebasah** [comment]
**Observations**:
1. Real-time logs are generated by agents even when their status shows "disconnected" in the Wazuh dashboard. Agents might appear disconnected because:
 -  The reconnection interval is set to 60 seconds, meaning there’s a delay before agents attempt to reconnect after losing connection.
 -  Resource limitations 
2. Agents disconnect for extended periods (e.g., a week) and only reconnect after the user's machine is restarted.

**Comment by yannicksiewe** [comment]
Check result in the next Daily

**Comment by Calebasah** [comment]
**Observation:**
Not all worker nodes in the Wazuh cluster are being utilized.
Worker nodes are responsible for managing keep-alive jobs, which may affect the accuracy of agent statuses if underused or unbalanced.
![Image](https://github.com/user-attachments/assets/a8905e29-bcce-4e54-a026-3b09c45974c5)

**Comment by Calebasah** [comment]
WIP @stephane-segning

**Comment by Calebasah** [comment]
#### Observation:
1. **Update Wazuh Version:**
2. **Check the Load Balancer:** Ensure the load balancer is properly distributing traffic across all nodes
3. **Agents Disconnection Time (20s):** This could cause agents to disconnect frequently.
![Image](https://github.com/user-attachments/assets/9a3205ee-4d88-4c92-9e45-2942b5e762b8)

**Comment by yannicksiewe** [comment]
Comment:
- [ ] Agent version Upgrade is on-progress by @ArmandMeppa 
- [ ] Upgrade feature on wazuh require good internet connection
- [ ] LoadBalancer changes are on-progress @stephane-segning 
- [ ] Agents Disconnection Time (20s) is already deploy in dev and in review @Calebasah

**Comment by MarantosGeorge** [comment]
Done
